2025-02-21 18:41:24,802 root INFO: Getting started with the program.
2025-02-21 18:41:24,811 root INFO: Устаревшие лог-файлы удалены.
2025-02-21 18:41:24,813 root INFO: Data for connection are loaded
2025-02-21 18:41:25,371 root INFO: Database connection is completed successfully.
2025-02-21 18:41:25,371 root INFO: Sending a request for data in the range from 2023-04-01 00:00:00 to 2023-04-01 00:02:00.
2025-02-21 18:42:09,666 root INFO: The request was completed successfully.
2025-02-21 18:42:10,186 root INFO: Data is successfully loaded into the database.
2025-02-21 18:42:10,186 root INFO: All data for the selected period has been loaded into the database. The connection to the database was interrupted.
2025-02-21 18:42:10,187 root INFO: Data has been aggregated successfully.
2025-02-21 18:42:13,075 root INFO: Connection to Google Sheets is complete.
2025-02-21 18:42:13,943 root INFO: Aggregated data written to Google Sheets successfully
2025-02-21 20:56:59,082 root INFO: Getting started with the program.
2025-02-21 20:56:59,088 root INFO: Устаревшие лог-файлы удалены.
2025-02-21 20:56:59,090 root INFO: Data for connection are loaded
2025-02-21 20:56:59,660 root INFO: Database connection is completed successfully.
2025-02-21 20:56:59,660 root INFO: Sending a request for data in the range from 2023-04-01 00:00:00 to 2023-04-01 00:02:00.
2025-02-21 20:57:41,291 root INFO: The request was completed successfully.
2025-02-21 20:57:41,812 root INFO: Data is successfully loaded into the database.
2025-02-21 20:57:41,812 root INFO: All data for the selected period has been loaded into the database. The connection to the database was interrupted.
2025-02-21 20:57:41,813 root INFO: Data has been aggregated successfully.
2025-02-21 20:57:44,595 root INFO: Connection to Google Sheets is complete.
2025-02-21 20:57:44,948 root INFO: Aggregated data written to Google Sheets successfully
2025-02-21 20:57:45,339 root ERROR: name 'project214' is not defined
Traceback (most recent call last):
  File "C:\Users\Владимир\PycharmProjects\pythonProject1\python_project_214.py", line 236, in <module>
    server.login(project214, usEN4kZWbgvQiBfy72Dw)
                 ^^^^^^^^^^
NameError: name 'project214' is not defined
2025-02-21 20:59:00,217 root INFO: Getting started with the program.
2025-02-21 20:59:00,222 root INFO: Устаревшие лог-файлы удалены.
2025-02-21 20:59:00,223 root INFO: Data for connection are loaded
2025-02-21 20:59:00,323 root INFO: Database connection is completed successfully.
2025-02-21 20:59:00,323 root INFO: Sending a request for data in the range from 2023-04-01 00:00:00 to 2023-04-01 00:02:00.
2025-02-21 20:59:43,002 root INFO: The request was completed successfully.
2025-02-21 20:59:43,025 root INFO: Data is successfully loaded into the database.
2025-02-21 20:59:43,026 root INFO: All data for the selected period has been loaded into the database. The connection to the database was interrupted.
2025-02-21 20:59:43,026 root INFO: Data has been aggregated successfully.
2025-02-21 20:59:44,912 root INFO: Connection to Google Sheets is complete.
2025-02-21 20:59:45,230 root INFO: Aggregated data written to Google Sheets successfully
2025-02-21 20:59:45,429 root ERROR: name 'project214' is not defined
Traceback (most recent call last):
  File "C:\Users\Владимир\PycharmProjects\pythonProject1\python_project_214.py", line 236, in <module>
    server.login(project214, usEN4kZWbgvQiBfy72Dw)
                 ^^^^^^^^^^
NameError: name 'project214' is not defined
2025-02-21 21:00:18,835 root INFO: Getting started with the program.
2025-02-21 21:00:18,840 root INFO: Устаревшие лог-файлы удалены.
2025-02-21 21:00:18,841 root INFO: Data for connection are loaded
2025-02-21 21:00:18,949 root INFO: Database connection is completed successfully.
2025-02-21 21:00:18,949 root INFO: Sending a request for data in the range from 2023-04-01 00:00:00 to 2023-04-01 00:02:00.
2025-02-21 21:01:01,758 root INFO: The request was completed successfully.
2025-02-21 21:01:01,780 root INFO: Data is successfully loaded into the database.
2025-02-21 21:01:01,780 root INFO: All data for the selected period has been loaded into the database. The connection to the database was interrupted.
2025-02-21 21:01:01,780 root INFO: Data has been aggregated successfully.
2025-02-21 21:01:03,510 root INFO: Connection to Google Sheets is complete.
2025-02-21 21:01:04,368 root INFO: Aggregated data written to Google Sheets successfully
2025-02-21 21:01:06,673 root ERROR: (535, b'5.7.0 NEOBHODIM parol prilozheniya https://help.mail.ru/mail/security/protection/external / Application password is REQUIRED')
Traceback (most recent call last):
  File "C:\Users\Владимир\PycharmProjects\pythonProject1\python_project_214.py", line 236, in <module>
    server.login('project214', 'usEN4kZWbgvQiBfy72Dw')
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владимир\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Владимир\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ~~~~~~~~~^
        authmethod, getattr(self, method_name),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        initial_response_ok=initial_response_ok)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владимир\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.0 NEOBHODIM parol prilozheniya https://help.mail.ru/mail/security/protection/external / Application password is REQUIRED')
2025-02-21 21:12:53,460 root INFO: Getting started with the program.
2025-02-21 21:12:53,465 root INFO: Устаревшие лог-файлы удалены.
2025-02-21 21:12:53,467 root INFO: Data for connection are loaded
2025-02-21 21:12:53,988 root INFO: Database connection is completed successfully.
2025-02-21 21:12:53,989 root INFO: Sending a request for data in the range from 2023-04-01 00:00:00 to 2023-04-01 00:02:00.
2025-02-21 21:13:37,698 root INFO: The request was completed successfully.
2025-02-21 21:13:38,149 root INFO: Data is successfully loaded into the database.
2025-02-21 21:13:38,150 root INFO: All data for the selected period has been loaded into the database. The connection to the database was interrupted.
2025-02-21 21:13:38,150 root INFO: Data has been aggregated successfully.
2025-02-21 21:13:41,543 root INFO: Connection to Google Sheets is complete.
2025-02-21 21:13:42,515 root INFO: Aggregated data written to Google Sheets successfully
2025-02-21 21:13:44,829 root ERROR: (535, b'5.7.0 NEOBHODIM parol prilozheniya https://help.mail.ru/mail/security/protection/external / Application password is REQUIRED')
Traceback (most recent call last):
  File "C:\Users\Владимир\PycharmProjects\pythonProject1\python_project_214.py", line 236, in <module>
    server.login('project_214', 'ybdMAexXrP2NrwXj5dvz')
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владимир\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Владимир\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ~~~~~~~~~^
        authmethod, getattr(self, method_name),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        initial_response_ok=initial_response_ok)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владимир\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.0 NEOBHODIM parol prilozheniya https://help.mail.ru/mail/security/protection/external / Application password is REQUIRED')
2025-02-21 21:16:55,347 root INFO: Getting started with the program.
2025-02-21 21:16:55,352 root INFO: Устаревшие лог-файлы удалены.
2025-02-21 21:16:55,353 root INFO: Data for connection are loaded
2025-02-21 21:16:55,444 root INFO: Database connection is completed successfully.
2025-02-21 21:16:55,444 root INFO: Sending a request for data in the range from 2023-04-01 00:00:00 to 2023-04-01 00:02:00.
2025-02-21 21:17:36,781 root INFO: The request was completed successfully.
2025-02-21 21:17:36,787 root INFO: Data is successfully loaded into the database.
2025-02-21 21:17:36,787 root INFO: All data for the selected period has been loaded into the database. The connection to the database was interrupted.
2025-02-21 21:17:36,787 root INFO: Data has been aggregated successfully.
2025-02-21 21:17:39,939 root INFO: Connection to Google Sheets is complete.
2025-02-21 21:17:40,866 root INFO: Aggregated data written to Google Sheets successfully
2025-02-21 21:17:43,232 root ERROR: (535, b'5.7.0 NEOBHODIM parol prilozheniya https://help.mail.ru/mail/security/protection/external / Application password is REQUIRED')
Traceback (most recent call last):
  File "C:\Users\Владимир\PycharmProjects\pythonProject1\python_project_214.py", line 236, in <module>
    server.login('project_214', 'ybdMAexXrP2NrwXj5dvz')
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владимир\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Владимир\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ~~~~~~~~~^
        authmethod, getattr(self, method_name),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        initial_response_ok=initial_response_ok)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владимир\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.0 NEOBHODIM parol prilozheniya https://help.mail.ru/mail/security/protection/external / Application password is REQUIRED')
2025-02-21 21:26:58,009 root INFO: Getting started with the program.
2025-02-21 21:26:58,014 root INFO: Устаревшие лог-файлы удалены.
2025-02-21 21:26:58,015 root INFO: Data for connection are loaded
2025-02-21 21:26:58,112 root INFO: Database connection is completed successfully.
2025-02-21 21:26:58,112 root INFO: Sending a request for data in the range from 2023-04-01 00:00:00 to 2023-04-01 00:02:00.
2025-02-21 21:27:38,998 root INFO: The request was completed successfully.
2025-02-21 21:27:39,007 root INFO: Data is successfully loaded into the database.
2025-02-21 21:27:39,007 root INFO: All data for the selected period has been loaded into the database. The connection to the database was interrupted.
2025-02-21 21:27:39,007 root INFO: Data has been aggregated successfully.
2025-02-21 21:27:42,572 root INFO: Connection to Google Sheets is complete.
2025-02-21 21:27:43,608 root INFO: Aggregated data written to Google Sheets successfully
